services:
  - type: web
    name: travelcompanion-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: travelcompanion-db
          property: connectionString

  - type: web
    name: travelcompanion-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: travelcompanion-api
          type: web
          property: url

databases:
  - name: travelcompanion-db
    databaseName: travelcompanion
    ipAllowList: []
